### PR TITLE
Mapp 1.1.1 (similar to 1.1) to autobuild

### LINKED ISSUE #97: Updated env for mapp-python not pushed to DockerHub
With #95 and #96 we updated an env. for some modules in MAPP.
However, the image for `1.1` is still not available at DockerHub:
https://hub.docker.com/r/zavolab/mapp_base_python/tags?page=1&ordering=last_updated

is there a wasy to manually trigger the push?

### PR DESCRIPTION
**Pull request by fgypas**
Mapp 1.1.1 (similar to 1.1) to autobuild Fixes #97

### CODE REVIEW

**Comment by AngryMaciek** [comment]
Local build passed but in the nick of time.
However, if upon PR merge the CI runs both local and remote build 30min would not be enough...
I would adjust to" `travis wait 60` in the CI YAML...

**Comment by fgypas** [comment]
So, can you then please push the change here first (this branch)?

**Comment by AngryMaciek** [comment]
Done. Once these checks pass it is ready to merge.

**Comment by AngryMaciek** [comment]
@fgypas: could you please merge this PR?

**Pull request merged**
